[package]
name = "Retail"
description = "A retail shop management mod for Morrowind."
authors = [ "JosephMcKean",]
version = "0.1"

[tools.mwse]
lua-mod = "retail"

[dependencies]
assets = [ "Retail.esp", "MWSE/mods/retail",]

[dependencies.mwse]
buildnumber = 3066

[dependencies.mge-xe]
version = ">=0.15.2"

[dependencies.mods."The Crafting Framework"]
mwse-module = "CraftingFramework"
version = "^1.4.1"
url = "https://www.nexusmods.com/morrowind/mods/51009"
